/**
 * YUAI Marketop — 샘플 제품·블로그 데이터.
 * Nexus AI 연동 시 API로 대체 가능.
 */
export const CATEGORIES = [
  { id: "all", labelKey: "products.categoryAll" },
  { id: "amazon", labelKey: "products.categoryAmazon" },
  { id: "shein", labelKey: "products.categoryShein" },
  { id: "temu", labelKey: "products.categoryTemu" },
];

/** 제품별 AI 분석 확장 데이터. specs: { labelKey, value } 또는 { label, value } */
export const ALL_PRODUCTS = [
  {
    id: "amazon-pick-1",
    slug: "amazon-pick-1",
    title: "Wireless Earbuds Pro",
    description: "Noise-cancelling, 24h battery. Best for work and travel.",
    price: "$49.99",
    image: "https://images.unsplash.com/photo-1598331668826-20cecc596b86?w=400&h=300&fit=crop",
    category: "amazon",
    tags: ["audio", "tech", "bestseller"],
    goId: "amazon-pick",
    insight: "Global demand for affordable ANC earbuds grew 40% YoY. This model ranks in top 3 for LATAM price segment.",
    analysisUpdated: "2025-02",
    marketSnapshot: { growth: "40%", trendKey: "product.snapshotTrendANC", regionKey: "product.regionLATAM" },
    bestFor: ["product.bestFor2534", "product.bestForLATAM", "product.bestForWFH"],
    specs: [
      { labelKey: "product.specBattery", value: "24h" },
      { labelKey: "product.specANC", value: "Yes" },
      { labelKey: "product.specConnectivity", value: "Bluetooth 5.2" },
    ],
    trendData: [58, 65, 72, 78, 85, 88],
  },
  {
    id: "shein-dress-1",
    slug: "shein-dress-1",
    title: "Summer Midi Dress",
    description: "Lightweight, sustainable fabric. Trend-aligned for 2025.",
    price: "$24.99",
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=300&fit=crop",
    category: "shein",
    tags: ["fashion", "summer", "trending"],
    goId: "shein",
    insight: "Midi lengths and earth tones are dominating social-led searches in ES/MX. This style matches current algorithm favor.",
    analysisUpdated: "2025-02",
    marketSnapshot: { growth: "28%", trendKey: "product.snapshotTrendMidi", regionKey: "product.regionESMX" },
    bestFor: ["product.bestFor2534", "product.bestForESMX", "product.bestForSocial"],
    specs: [
      { labelKey: "product.specMaterial", value: "Sustainable blend" },
      { labelKey: "product.specCare", value: "Machine wash" },
      { labelKey: "product.specSizes", value: "XS–XL" },
    ],
    trendData: [62, 70, 78, 82, 86, 90],
  },
  {
    id: "temu-gadget-1",
    slug: "temu-gadget-1",
    title: "Portable Power Bank 20K",
    description: "Fast charge, compact. Ideal for creators on the go.",
    price: "$18.99",
    image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=300&fit=crop",
    category: "temu",
    tags: ["tech", "travel", "gadget"],
    goId: "temu",
    insight: "Power banks above 15K mAh are among the fastest-growing SKUs in cross-border to LATAM. Strong conversion in 25–34 segment.",
    analysisUpdated: "2025-02",
    marketSnapshot: { growth: "35%", trendKey: "product.snapshotTrendPower", regionKey: "product.regionLATAM" },
    bestFor: ["product.bestFor2534", "product.bestForLATAM", "product.bestForCreators"],
    specs: [
      { labelKey: "product.specCapacity", value: "20,000 mAh" },
      { labelKey: "product.specOutput", value: "USB-C 22.5W" },
      { labelKey: "product.specWeight", value: "~380g" },
    ],
    trendData: [55, 62, 71, 76, 82, 87],
  },
  {
    id: "amazon-pick-2",
    slug: "amazon-pick-2",
    title: "Organic Skincare Set",
    description: "Clean ingredients, dermatologist-tested. K-beauty inspired.",
    price: "$34.99",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=300&fit=crop",
    category: "amazon",
    tags: ["beauty", "skincare", "organic"],
    goId: "amazon-pick",
    insight: "K-beauty and clean beauty continue to drive search growth in Americas. Set format increases AOV and repeat intent.",
    analysisUpdated: "2025-02",
    marketSnapshot: { growth: "22%", trendKey: "product.snapshotTrendKBeauty", regionKey: "product.regionAmericas" },
    bestFor: ["product.bestFor2534", "product.bestForAmericas", "product.bestForRepeat"],
    specs: [
      { labelKey: "product.specIngredients", value: "Clean, dermatologist-tested" },
      { labelKey: "product.specItems", value: "3-piece set" },
      { labelKey: "product.specCert", value: "Cruelty-free" },
    ],
    trendData: [68, 72, 75, 78, 80, 84],
  },
  {
    id: "shein-shoes-1",
    slug: "shein-shoes-1",
    title: "Platform Sneakers",
    description: "Comfortable everyday platform. Multiple colorways.",
    price: "$32.00",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop",
    category: "shein",
    tags: ["shoes", "trending", "casual"],
    goId: "shein",
    insight: "Platform and chunky soles remain in top search terms. This style performs well in both feed and search campaigns.",
    analysisUpdated: "2025-02",
    marketSnapshot: { growth: "18%", trendKey: "product.snapshotTrendPlatform", regionKey: "product.regionESMX" },
    bestFor: ["product.bestFor1824", "product.bestFor2534", "product.bestForSocial"],
    specs: [
      { labelKey: "product.specMaterial", value: "Synthetic upper" },
      { labelKey: "product.specSole", value: "Chunky platform" },
      { labelKey: "product.specSizes", value: "EU 35–42" },
    ],
    trendData: [64, 70, 76, 80, 83, 85],
  },
  {
    id: "temu-home-1",
    slug: "temu-home-1",
    title: "LED Desk Lamp",
    description: "Adjustable brightness, USB port. Minimal design.",
    price: "$22.99",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=300&fit=crop",
    category: "temu",
    tags: ["home", "office", "lighting"],
    goId: "temu",
    insight: "Home office and desk accessories show sustained demand. LED with USB is a high-intent keyword in our reports.",
    analysisUpdated: "2025-02",
    marketSnapshot: { growth: "15%", trendKey: "product.snapshotTrendHomeOffice", regionKey: "product.regionLATAM" },
    bestFor: ["product.bestFor2534", "product.bestForLATAM", "product.bestForWFH"],
    specs: [
      { labelKey: "product.specBrightness", value: "Adjustable" },
      { labelKey: "product.specUSB", value: "Built-in port" },
      { labelKey: "product.specBase", value: "Clamp / desk" },
    ],
    trendData: [60, 65, 72, 75, 78, 82],
  },
];

/** 메인/랜딩에서 노출할 인기 제품 (ALL_PRODUCTS 서브셋) */
export const POPULAR_PRODUCTS = ALL_PRODUCTS.slice(0, 4);

export const BLOG_POSTS = [
  {
    id: "1",
    slug: "latam-ecommerce-2025",
    titleKey: "blog.post1Title",
    excerptKey: "blog.post1Excerpt",
    date: "2025-02-20",
    categoryKey: "blog.categoryIntel",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=320&fit=crop",
  },
  {
    id: "2",
    slug: "trends-social-shopping",
    titleKey: "blog.post2Title",
    excerptKey: "blog.post2Excerpt",
    date: "2025-02-15",
    categoryKey: "blog.categoryTrends",
    image: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=600&h=320&fit=crop",
  },
  {
    id: "3",
    slug: "affiliate-best-practices",
    titleKey: "blog.post3Title",
    excerptKey: "blog.post3Excerpt",
    date: "2025-02-10",
    categoryKey: "blog.categoryReport",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=320&fit=crop",
  },
];
